In [22]:
import numpy as np
import pandas as pd
from pathlib import Path

## Combining the data

In [32]:
demandDf = pd.read_csv(
    "DataRaw/demand.csv",
    dtype={
        "Date": "float64",     # Excel serials may come as float
        "Period": "int16",
        "OperationalLessIndustrial": "float64",
        "Industrial": "float64",
    }
)

In [34]:
demandDf.head()

      Date  Period  OperationalLessIndustrial   Industrial
0  37257.0       1                3535.867064  1086.132936
1  37257.0       2                3383.499028  1088.500972
2  37257.0       3                3655.527552  1084.472448
3  37257.0       4                3510.446636  1085.553364
4  37257.0       5                3294.697156  1081.302844

In [37]:
midnight = pd.to_datetime(demandDf["Date"], unit="d", origin="1899-12-30")
demandDf["timestamp"] = midnight + pd.to_timedelta((demandDf["Period"] - 1) * 30, unit="m")
demandDf["Demand"] = demandDf["OperationalLessIndustrial"] + demandDf["Industrial"]

In [42]:
demandDf.tail()

,Date,Period,OperationalLessIndustrial,Industrial,timestamp,Demand
230779,42064.0,44,NaN,NaN,2015-03-01 21:30:00,NaN
230780,42064.0,45,NaN,NaN,2015-03-01 22:00:00,NaN
230781,42064.0,46,NaN,NaN,2015-03-01 22:30:00,NaN
230782,42064.0,47,NaN,NaN,2015-03-01 23:00:00,NaN
230783,42064.0,48,NaN,NaN,2015-03-01 23:30:00,NaN

In [39]:
per_day = demandDf.groupby(demandDf["timestamp"].dt.date).size()
assert per_day.ge(48).all(), "Some days have less than 48 half-hour periods"

In [40]:
dupes = demandDf["timestamp"].duplicated(keep=False).sum()
assert dupes == 0, f"Found {dupes} duplicated timestamps."

In [43]:
demandDf2 = pd.read_csv("DataRaw/demand.csv")

In [44]:
demandDf2.tail()

         Date  Period  OperationalLessIndustrial  Industrial
230779  42064      44                        NaN         NaN
230780  42064      45                        NaN         NaN
230781  42064      46                        NaN         NaN
230782  42064      47                        NaN         NaN
230783  42064      48                        NaN         NaN